/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('@spartan-ng/ui-core/hlm-tailwind-preset')],
  content: [
    "./src/**/*.{html,ts}",
    "./components/**/*.{html,ts}",
    "./libs/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#d1dbec',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dfe9fa',
        'surface-container-highest': '#d9e3f4',
        'on-surface': '#121c28',
        'on-surface-variant': '#5c403c',
        'inverse-surface': '#27313e',
        'inverse-on-surface': '#eaf1ff',
        outline: '#916f6b',
        'outline-variant': '#e6bdb8',
        'surface-tint': '#bf0715',
        primary: '#b70011',
        'on-primary': '#ffffff',
        'primary-container': '#dc2626',
        'on-primary-container': '#fff6f5',
        'inverse-primary': '#ffb4ab',
        secondary: '#b02d29',
        'on-secondary': '#ffffff',
        'secondary-container': '#ff665c',
        'on-secondary-container': '#690007',
        tertiary: '#605758',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#796f70',
        'on-tertiary-container': '#fff5f5',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ab',
        'on-primary-fixed': '#410002',
        'on-primary-fixed-variant': '#93000b',
        'secondary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#ffb4ac',
        'on-secondary-fixed': '#410002',
        'on-secondary-fixed-variant': '#8e1214',
        'tertiary-fixed': '#eddfe0',
        'tertiary-fixed-dim': '#d0c3c5',
        'on-tertiary-fixed': '#211a1b',
        'on-tertiary-fixed-variant': '#4d4546',
        background: '#f8f9ff',
        'on-background': '#121c28',
        'surface-variant': '#d9e3f4',
        'ruby-accent': '#BE123C',
        'soft-pink': '#FFE4E6',
        'border-subtle': '#E5E7EB',
        'surface-muted': '#F9FAFB',
      },
      fontFamily: {
        heading: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        'pill': '9999px',
      },
      spacing: {
        base: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'kanban-column-width': '320px',
      },
      boxShadow: {
        'drag': '0 8px 24px rgba(190, 18, 60, 0.15)',
      }
    },
  },
  plugins: [],
}